// Mock data for challenges
export const mockChallenges = [
  {
    id: 'challenge-1',
    stackId: 'stack-1',
    title: 'AI로 블로그 썸네일 만들기',
    description: '이 챌린지는 디자인 작업을 AI 툴로 효율적으로 수행하는 방법을 배울 수 있습니다.',
    instructions: [
      '1단계: 필요한 툴 설치하기',
      '2단계: 프롬프트 작성하기',
      '3단계: 결과물 생성하기',
      '4단계: 결과 공유하기',
    ],
    rewardBadge: '디자인 마스터',
    difficulty: 'beginner',
    estimatedTime: 15,
    createdAt: new Date(),
  },
  {
    id: 'challenge-2',
    stackId: 'stack-2',
    title: '자동 이메일 응답 시스템 구축',
    description: '이 챌린지는 자동화 작업을 AI 툴로 효율적으로 수행하는 방법을 배울 수 있습니다.',
    instructions: [
      '1단계: 이메일 템플릿 준비',
      '2단계: 자동화 툴 설정',
      '3단계: 테스트 및 배포',
    ],
    rewardBadge: '자동화 전문가',
    difficulty: 'intermediate',
    estimatedTime: 30,
    createdAt: new Date(),
  },
];

// Mock data for stacks
export const mockStacks = [
  {
    id: 'stack-1',
    title: '블로그 콘텐츠 제작 세트',
    description: '블로그 글 작성과 이미지 생성을 위한 툴 조합',
    toolIds: ['tool-1', 'tool-2', 'tool-3'],
    creatorId: 'user-1',
    isPublic: true,
    isFeatured: true,
    purpose: '블로그 콘텐츠를 쉽고 빠르게 제작',
    steps: ['아이디어 구상', '글 작성', '이미지 생성'],
    saveCount: 24,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'stack-2',
    title: '개인 프로젝트 관리 스택',
    description: '프로젝트 관리와 문서화를 위한 툴 조합',
    toolIds: ['tool-4', 'tool-5'],
    creatorId: 'user-1',
    isPublic: false,
    isFeatured: false,
    purpose: '개인 프로젝트를 체계적으로 관리',
    steps: ['프로젝트 계획', '진행 상황 기록'],
    saveCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock data for tools
export const mockTools = [
  {
    id: 'tool-1',
    name: 'GPT-4',
    description: '최신 언어 모델을 활용한 텍스트 생성 툴',
    category: '텍스트 생성',
    isFree: false,
    llmType: 'GPT-4',
    url: 'https://openai.com/gpt-4',
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tool-2',
    name: 'Canva',
    description: '이미지 및 디자인 제작 툴',
    category: '이미지 생성',
    isFree: true,
    url: 'https://www.canva.com/',
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tool-3',
    name: 'Notion',
    description: '문서화 및 협업 툴',
    category: '데이터 분석',
    isFree: true,
    url: 'https://www.notion.so/',
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tool-4',
    name: 'Trello',
    description: '프로젝트 관리 툴',
    category: '생산성',
    isFree: true,
    url: 'https://trello.com/',
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tool-5',
    name: 'Zapier',
    description: '자동화 워크플로우 툴',
    category: '자동화',
    isFree: false,
    url: 'https://zapier.com/',
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock user profile
export const mockUser = {
  id: 'user-1',
  displayName: '홍길동',
  email: 'user@example.com',
  avatar: '',
  level: 3,
  xp: 250,
  badges: ['텍스트 마스터 Lv.1', '이미지 생성 Lv.2', '자동화 전문가'],
  createdStacks: ['stack-1', 'stack-2'],
  savedStacks: ['stack-1'],
  completedChallenges: ['challenge-1'],
  ongoingChallenges: [],
  createdAt: new Date(),
}; 